export interface TitleCreator {
  role: '글' | '그림' | '원작' | '컬러' | '각색' | '기타';
  name: string;
}

export type GlobalCountryCode = 'us' | 'jp' | 'id' | 'fr' | 'tw' | 'th' | 'de' | 'es' | 'cn';

export const GLOBAL_COUNTRIES: { code: GlobalCountryCode; label: string; flag: string }[] = [
  { code: 'us', label: '북미', flag: '🇺🇸' },
  { code: 'jp', label: '일본', flag: '🇯🇵' },
  { code: 'id', label: '인도네시아', flag: '🇮🇩' },
  { code: 'fr', label: '프랑스', flag: '🇫🇷' },
  { code: 'tw', label: '대만', flag: '🇹🇼' },
  { code: 'th', label: '태국', flag: '🇹🇭' },
  { code: 'de', label: '독일', flag: '🇩🇪' },
  { code: 'es', label: '스페인', flag: '🇪🇸' },
  { code: 'cn', label: '중국', flag: '🇨🇳' },
];

export interface CountryPublishing {
  platform?: string;
  title?: string;
  status: '연재중' | '완결' | '미진출' | '계약중' | '준비중';
  startDate?: string;
  endDate?: string;
  episodeCount?: number;
  note?: string;
}

export type TitleStatus = '연재중' | '완결' | '휴재' | '준비중';
export type SerialType = '요일웹툰' | '매일+' | '기타';
export type DayOfWeek = '월요일' | '화요일' | '수요일' | '목요일' | '금요일' | '토요일' | '일요일';
export type TeamLabel = '팀 박태준' | '팀 병장' | '팀 유호빈' | 'MUTE' | 'MAJOR' | '팀 꿀빨' | '팀 숭늉' | '전략기획팀' | '그 외';
export const TEAM_LABELS: TeamLabel[] = ['팀 박태준', '팀 병장', '팀 유호빈', 'MUTE', 'MAJOR', '팀 꿀빨', '팀 숭늉', '전략기획팀', '그 외'];

export type SecondaryBizCategory = '출판' | '드라마' | '영화' | '애니메이션' | '그 외';

export interface SecondaryBizItem {
  category: SecondaryBizCategory;
  title?: string;
  status: string;
  partner?: string;
  note?: string;
}

export interface TitleMasterInfo {
  slug: string;
  workId?: string;
  title: string;
  titleUrl?: string;
  teamLabel?: TeamLabel;
  status: TitleStatus;
  creators: TitleCreator[];
  platform: string;
  serialType: SerialType;
  dayOfWeek?: DayOfWeek;
  startDate: string;
  endDate?: string;
  nonExclusiveDate?: string;
  episodeCount: number;
  ageRating: string;
  mainGenre: string;
  subGenre?: string;
  keywords: string[];
  element: string;
  logline: string;
  thumbnailUrl?: string;
  globalInfo: Partial<Record<GlobalCountryCode, CountryPublishing>>;
  secondaryBiz: SecondaryBizItem[];
  notes: string;
}

export const TITLE_MASTER_DATA: TitleMasterInfo[] = [
  {
    slug: 'lookism',
    title: '외모지상주의',
    status: '연재중',
    creators: [{ role: '글', name: '박태준' }, { role: '그림', name: '박태준' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '금요일',
    startDate: '2014-11-20',
    episodeCount: 601,
    ageRating: '15+',
    mainGenre: '기타',
    keywords: [],
    element: '',
    logline: '',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'hannam-dong-k-house',
    title: '한남동케이하우스',
    status: '완결',
    creators: [{ role: '글', name: '박태준' }, { role: '그림', name: '박태준' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '수요일',
    startDate: '2018-12-05',
    endDate: '2019-10-30',
    nonExclusiveDate: '2022-10-29',
    episodeCount: 48,
    ageRating: '12+',
    mainGenre: '기타',
    keywords: [],
    element: '',
    logline: '',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'life-or-death',
    title: '인생존망',
    status: '완결',
    creators: [{ role: '글', name: '박태준' }, { role: '그림', name: '전선욱' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '일요일',
    startDate: '2019-11-08',
    endDate: '2020-11-08',
    nonExclusiveDate: '2023-11-08',
    episodeCount: 57,
    ageRating: '15+',
    mainGenre: '드라마',
    subGenre: '액션',
    keywords: ['드라마', '시간여행', '속죄', '성장', '우정'],
    element: '왕년에 일진이었던 장안철, 찐따 김진우의 고등학교 시절 몸에서 깨어나면서, 인생을 리셋하기 위한 싸움이 시작된다.',
    logline: '학교 폭력으로 깊은 상처를 입은 김진우는 말더듬이가 되고 자존감도 무너진 채 살아간다. 그는 성공과 복수의 꿈만을 붙잡고 버틴다. 하지만 아르바이트하는 가게의 주인이 과거 자신을 괴롭힌 최악의 양아치 안철 장이라는 사실을 알게 되면서, 그들의 조롱에 분개해 무모하게 추락하고 만다.\n\n그 순간, 기묘한 일이 벌어진다. 스물한 살의 안철의 영혼이 과거 고등학교 2학년, 열여덟 살 진우의 몸 속으로 들어온 것이다. 진우의 저주에 묶인 그는, 진우의 미래를 망쳐놓은 네 가지 사건을 되돌리고 동시에 자신이었던 괴물 같은 소년을 갱생시켜야만 한다.',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'viral-hit',
    title: '싸움독학',
    status: '완결',
    creators: [{ role: '글', name: '박태준만화회사' }, { role: '그림', name: '김정현' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '토요일',
    startDate: '2019-11-16',
    endDate: '2024-02-24',
    nonExclusiveDate: '2027-02-23',
    episodeCount: 223,
    ageRating: '15+',
    mainGenre: '기타',
    keywords: [],
    element: '',
    logline: '',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'desire-diary',
    title: '욕망일기',
    status: '완결',
    creators: [{ role: '글', name: '김꿀빨' }, { role: '그림', name: '박태준만화회사' }, { role: '그림', name: '김꿀빨' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '금요일',
    startDate: '2020-12-25',
    endDate: '2021-09-17',
    nonExclusiveDate: '2024-09-16',
    episodeCount: 39,
    ageRating: '15+',
    mainGenre: '기타',
    keywords: [],
    element: '',
    logline: '',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'quest-supremacy',
    title: '퀘스트지상주의',
    status: '완결',
    creators: [
      { role: '글', name: '박태준만화회사' },
      { role: '글', name: '유누니' },
      { role: '그림', name: '박태준만화회사' },
      { role: '그림', name: '태완' },
    ],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '월요일',
    startDate: '2021-10-24',
    endDate: '2025-03-02',
    nonExclusiveDate: '2028-03-01',
    episodeCount: 174,
    ageRating: '15+',
    mainGenre: '액션',
    subGenre: '판타지',
    keywords: [],
    element: '뭐 하나 잘난 것 없는 평범한 고등학생 ‘김수현’의 눈앞에 갑자기 퀘스트창이 나타났다!\n\n현실이 게임처럼 수치화된 세계에서 평범한 소년이 퀘스트를 통해 성장하며 ‘플레이어’로 거듭나는 과정에서 드라마적인 요소를 녹인 현대 판타지 성장 서사!',
    logline: '뭐 하나 잘난 것 없는 평범한 고등학생 ‘김수현’의 눈앞에 갑자기 퀘스트창이 나타났다!\n첫 번째 퀘스트, [엄마한테 사과하기]를 완료한 수현은 보상으로 키가 3cm 커지게 되는데!\n \n‘퀘스트 엄청 쉽잖아?! 어떤 퀘스트든 완료해주마! 그런데 다음 퀘스트가?’\n \n[system] 학교 일진녀와 키스하십시오\n \n이렇게 퀘스트를 완료해가며 강북을 둘러싼 4개 학교의 세력전 속에서 그는 점차 핵심적인 인물로 성장하게 되고 권력 판도를 바꾸는 존재로 부상한다. 그러나 그와 같은 시스템을 사용하는 또 다른 인물이 존재한다는 사실이 드러나면서 이 게임은 단순한 성장 스토리를 넘어 서게 되는데...',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'manager-kim',
    title: '김부장',
    status: '연재중',
    creators: [{ role: '글', name: '박태준만화회사' }, { role: '글', name: '남자의 이야기' }, { role: '그림', name: '정종택' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '화요일',
    startDate: '2021-11-01',
    episodeCount: 214,
    ageRating: '15+',
    mainGenre: '기타',
    keywords: [],
    element: '가족을 지키기 위해 ‘평범한 가장’의 얼굴 뒤에 숨겨둔 능력을 다시 꺼내 드는 한 아버지를 통해 사회에서 소모되던 중년 남성의 삶을 부성의 의지와 책임으로 재정의하며 이를 통쾌한 액션으로 풀어내 해방감을 주는 작품!',
    logline: '“제발 안경 쓴 아저씨는 건들지 말자…”\n\n딸 ‘민지’를 위해 특수요원 일을 그만두고 평범한 회사원으로 살던 김부장은, 어느 날 민지가 흔적도 없이 사라지자 금기를 깨고 다시 전장으로 돌아간다. 감시하던 국가조차 적으로 돌린 채 단서를 쫓아 잠입과 추격을 이어가며, 민지 실종 뒤에 얽힌 조직과 권력의 실체를 하나씩 무너뜨린다.',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'passive-human',
    title: '소극적인간',
    status: '완결',
    creators: [{ role: '글', name: '다쓴총' }, { role: '그림', name: '다쓴총' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '목요일',
    startDate: '2021-11-04',
    endDate: '2022-04-07',
    nonExclusiveDate: '2025-04-06',
    episodeCount: 45,
    ageRating: '18+',
    mainGenre: '기타',
    keywords: [],
    element: '',
    logline: '',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'survival-coin',
    title: '존망코인',
    status: '완결',
    creators: [{ role: '글', name: '박태준만화회사' }, { role: '그림', name: '박태준만화회사' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '토요일',
    startDate: '2021-11-06',
    endDate: '2022-08-13',
    nonExclusiveDate: '2025-08-12',
    episodeCount: 41,
    ageRating: '15+',
    mainGenre: '기타',
    keywords: [],
    element: '',
    logline: '',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'show-me-the-lucky',
    title: '쇼미더럭키짱!',
    status: '완결',
    creators: [{ role: '글', name: '박태준' }, { role: '그림', name: '김성모' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '화요일',
    startDate: '2021-11-16',
    endDate: '2022-06-05',
    nonExclusiveDate: '2025-06-04',
    episodeCount: 146,
    ageRating: '15+',
    mainGenre: '기타',
    keywords: [],
    element: '',
    logline: '',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'sinrim-male-22',
    title: '신림/남/22',
    status: '완결',
    creators: [{ role: '글', name: '김꿀빨' }, { role: '그림', name: '박태준만화회사' }, { role: '그림', name: '김꿀빨' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '금요일',
    startDate: '2021-11-19',
    endDate: '2022-06-10',
    nonExclusiveDate: '2025-06-09',
    episodeCount: 59,
    ageRating: '18+',
    mainGenre: '기타',
    keywords: [],
    element: '',
    logline: '',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'highschool-girl-dragon',
    title: '여고생 드래곤',
    status: '완결',
    creators: [{ role: '글', name: '땅콩' }, { role: '그림', name: '땅콩' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '금요일',
    startDate: '2021-11-26',
    endDate: '2023-01-13',
    nonExclusiveDate: '2026-01-12',
    episodeCount: 121,
    ageRating: '12+',
    mainGenre: '기타',
    keywords: [],
    element: '',
    logline: '',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'magical-lunch-assassin-mage',
    title: '매지컬급식: 암살법사',
    status: '완결',
    creators: [{ role: '글', name: '웡웡이' }, { role: '그림', name: '웡웡이' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '일요일',
    startDate: '2022-02-27',
    endDate: '2024-03-03',
    nonExclusiveDate: '2027-03-03',
    episodeCount: 106,
    ageRating: 'ALL',
    mainGenre: '기타',
    keywords: [],
    element: '',
    logline: '',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'death-sentence-boy',
    title: '사형소년',
    status: '완결',
    creators: [{ role: '글', name: '박태준만화회사' }, { role: '글', name: '김숭늉' }, { role: '그림', name: '광산' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '토요일',
    startDate: '2022-05-28',
    endDate: '2023-10-28',
    nonExclusiveDate: '2026-10-27',
    episodeCount: 75,
    ageRating: '15+',
    mainGenre: '드라마',
    subGenre: '스릴러',
    keywords: ['싸이코패스', '살인마', '복수', '액션', '가족', '후회'],
    element: '악인을 벌하는 죄인이되리',
    logline: '대한민국을 뒤흔든 희대의 연쇄살인마 김신! 김신에게 가족을 잃은 지후는 또 다른 피해자 두석을 만나 인간병기로 훈련된다. 그리고 살인마를 맨주먹으로 때려죽이기 위해 스스로 교도소로 향하는데...\n\n\'우리나라는 97년 이후로 사형집행이 되지 않았어. 누군가는 집행해야 하지 않을까?\'',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'spy-age-18',
    title: '간첩18세',
    status: '완결',
    creators: [{ role: '글', name: '김꿀빨' }, { role: '그림', name: '김주인' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '금요일',
    startDate: '2022-08-26',
    endDate: '2023-09-22',
    nonExclusiveDate: '2026-09-21',
    episodeCount: 57,
    ageRating: '15+',
    mainGenre: '기타',
    keywords: [],
    element: '',
    logline: '',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'highschool-detective',
    title: '고교흥신소',
    status: '완결',
    creators: [{ role: '글', name: '김성모' }, { role: '그림', name: '김성모' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '화요일',
    startDate: '2022-11-01',
    endDate: '2023-02-07',
    nonExclusiveDate: '2026-02-06',
    episodeCount: 15,
    ageRating: '15+',
    mainGenre: '기타',
    keywords: [],
    element: '',
    logline: '',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'chest',
    title: '궤짝',
    status: '완결',
    creators: [{ role: '글', name: '박태준만화회사' }, { role: '글', name: '주범' }, { role: '그림', name: '지노' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '월요일',
    startDate: '2022-11-14',
    endDate: '2024-04-15',
    nonExclusiveDate: '2027-04-15',
    episodeCount: 75,
    ageRating: '15+',
    mainGenre: '기타',
    keywords: [],
    element: '',
    logline: '',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'was-a-boss',
    title: '보스였음',
    status: '휴재',
    creators: [{ role: '글', name: '박태준만화회사' }, { role: '글', name: '럭스' }, { role: '그림', name: '럭스' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '목요일',
    startDate: '2022-11-23',
    episodeCount: 129,
    ageRating: '15+',
    mainGenre: '판타지',
    subGenre: '드라마',
    keywords: ['탑', '마왕', '배틀', '초인', '액션', '헌터'],
    element: '탑의 마왕이었던 내가 현실에선 초보 헌터?!',
    logline: '<심연의 탑> 보스 바포메트는 자신과 호각으로 싸울 강한 헌터를 기다리고 있다. 반복되는 싸움에 지루함을 느끼던 찰나, 죽은 헌터들의 전리품에 의해 인간 세상에 흥미를 갖게 되고, 동시에 늘 자신이 바랬던 강한 헌터가 눈 앞에 나타나자 그를 보며 인간의 존재에 더욱 더 매료되기 시작한다. 급기야 바포메트는 스스로 인간이 되고자 하는데…',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'baek-xx',
    title: '백XX',
    status: '연재중',
    creators: [{ role: '글', name: '박태준만화회사' }, { role: '글', name: '병장' }, { role: '그림', name: '펀치킥' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '수요일',
    startDate: '2023-01-17',
    episodeCount: 151,
    ageRating: '15+',
    mainGenre: '기타',
    keywords: [],
    element: '',
    logline: '',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'bully-is-too-good-at-fighting',
    title: '왕따가 격투기를 너무 잘함',
    status: '연재중',
    creators: [
      { role: '글', name: '박태준만화회사' },
      { role: '글', name: '김꿀빨' },
      { role: '그림', name: '김꿀빨' },
      { role: '원작', name: '아몬드빵' },
    ],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '수요일',
    startDate: '2023-02-28',
    episodeCount: 145,
    ageRating: '15+',
    mainGenre: '기타',
    keywords: [],
    element: '',
    logline: '',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'castle2-above-all',
    title: '캐슬2: 만인지상',
    status: '연재중',
    creators: [{ role: '글', name: '박태준만화회사' }, { role: '글', name: '정연' }, { role: '그림', name: '정연' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '수요일',
    startDate: '2023-03-07',
    episodeCount: 131,
    ageRating: '15+',
    mainGenre: '액션',
    subGenre: '느와르',
    keywords: ['킬러', '복수', '시리어스', '캐슬'],
    element: '복수를 위해 칼을 갈아온 특급 킬러 \'김신\', 뒷세계 \'절대 권력\'과의 목숨 건 한판 승부!',
    logline: '삼합회, 야쿠자, 러시아 킬러, 조폭 세력이 연대한 뒷세계 절대 권력 \'캐슬\'. \n흑룡강 호랑이라 불리는 한국인 러시아 킬러 \'김신\'.\n\n아버지와 스승의 복수를 위하여 한국으로 돌아온 \'김신\'은 뒷세계 절대 권력 \'캐슬\'을 무너뜨리기 위하여 전국의 남자들을 모아 \n\'백의\'를 조직하여 \'캐슬\'에 입성한다. 그렇게 캐슬 내부로 들어가 적과의 동침을 시작하는데.. \n\n과연 김신은 자신이 염원하던 대로 캐슬을 무너뜨리고 복수를 완성할 수 있을까."',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'juvenile-offender',
    title: '촉법소년',
    status: '완결',
    creators: [{ role: '글', name: '박태준만화회사' }, { role: '글', name: '남자의 이야기' }, { role: '그림', name: '정종택' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '목요일',
    startDate: '2023-04-05',
    endDate: '2024-10-23',
    nonExclusiveDate: '2027-10-23',
    episodeCount: 82,
    ageRating: '15+',
    mainGenre: '액션',
    subGenre: '드라마',
    keywords: ['복수', '액션', '참교육', '사회고발'],
    element: '대한민국은 X같은 법들로 가득하다!\n\n나를 지옥으로 밀어넣고도 처벌받지 않았던 ‘촉법소년’들에게 그 X같은 법의 결과물들에게, 지금부터 복수를 시작한다',
    logline: '',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'cheerful-outcast-re',
    title: '유쾌한 왕따(재)',
    status: '완결',
    creators: [{ role: '글', name: '박태준만화회사' }, { role: '글', name: '김숭늉' }, { role: '그림', name: '김숭늉' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    startDate: '2023-06-16',
    endDate: '2024-03-08',
    nonExclusiveDate: '2027-03-08',
    episodeCount: 76,
    ageRating: '18+',
    mainGenre: '기타',
    keywords: [],
    element: '',
    logline: '',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'ulzzang-era',
    title: '얼짱시대',
    status: '완결',
    creators: [{ role: '글', name: '박태준만화회사' }, { role: '그림', name: '남자의이야기' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '토요일',
    startDate: '2023-07-21',
    endDate: '2024-09-13',
    nonExclusiveDate: '2027-09-13',
    episodeCount: 76,
    ageRating: '15+',
    mainGenre: '드라마',
    subGenre: '액션',
    keywords: ['드라마', '시간여행', '레트로', '범죄', '가족'],
    element: '한 아들이 아버지의 과거로 돌아가, 청춘의 혼돈 속에서 가족의 운명을 다시 쓰려 한다.',
    logline: '“나 그 핸드폰 주인인데, 어디냐 너.” \n\n청춘과 낭만이 가득했던 그때 그시절, 가족을 버리고 떠난 끝에 비참하게 죽은 아버지의 오래된 휴대폰에 걸려온 한 통의 전화. \n기묘한 사건을 계기로 아들은 아버지의 청춘 시절로 시간여행을 하게 된다. \n\n샤기컷, 얼짱, 폭주족, 싸이월드, 버디버디 등 사라진 문화들이 되살아나는 혼돈의 시대 속에서 그는 아버지의 발자취를 따라가며 가족의 미래를 바꾸려 고군분투한다. 전국구 양아치와 격투기 선수의 충돌, 패륜과 우정을 넘나드는 드라마 속에서 웃음과 눈물, 향수를 동시에 선사한다.',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'lee-seob-romance',
    title: '이섭의 연애',
    status: '연재중',
    creators: [
      { role: '글', name: '김언희' },
      { role: '글', name: '248' },
      { role: '그림', name: '248.0' },
      { role: '원작', name: '김언희' },
    ],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '화요일',
    startDate: '2023-07-24',
    episodeCount: 81,
    ageRating: '15+',
    mainGenre: '로맨스',
    subGenre: '드라마',
    keywords: [],
    element: '',
    logline: '',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'body-explorer',
    title: '체탐자',
    status: '휴재',
    creators: [{ role: '글', name: '박태준만화회사' }, { role: '글', name: '병장' }, { role: '그림', name: '겸자' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '화요일',
    startDate: '2023-09-04',
    episodeCount: 82,
    ageRating: '15+',
    mainGenre: '기타',
    keywords: ['액션', '사극', '드라마', '가족', '블랙코미디', '전쟁', '역사'],
    element: '세종의 칼이 되어\n원수의 심장을 도단(刀斷)하라',
    logline: '‘세종의 비밀병기, 그림자부대 체탐자.’\n어린 시절부터 전쟁터를 헤매며 귀신의 그림자라 불리는 귀영.\n복수를 다짐하며 이 나라 최초의 특수부대 체탐자의 일원이 되기로 한다.',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'jinju',
    title: '진주',
    status: '완결',
    creators: [{ role: '글', name: '박태준만화회사' }, { role: '글', name: '백두' }, { role: '그림', name: '백두' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '월요일',
    startDate: '2023-11-12',
    endDate: '2025-03-10',
    nonExclusiveDate: '2028-03-09',
    episodeCount: 71,
    ageRating: '15+',
    mainGenre: '액션',
    subGenre: '느와르',
    keywords: ['시리어스', '헌신', '낭만', '백두유니버스', '레트로', '멜로'],
    element: '통, 독고, 블러드레인의 세계관을 공유한 희생과 사랑, 신의와 헌신의\n레트로 느와르 액션작품!',
    logline: '부산 최대 파벌 ‘주성회’의 보스 진주현.\n\n어느 날 안암 판정을 받은 그는 자신의 고향, 경남 진주로 내려가 게스트하우스 여주인 ‘현진주’를 만나\n난생처음 평범한 삶을 꿈꾸기 시작한다. 그러나 그가 새로운 삶을 꿈꿀수록 과거 뒷세계와의 지독한 악연이 그를 피할 수 없는 절체절명의 싸움으로 끌어들이는데...',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'life-or-death-2',
    title: '인생존망2',
    status: '완결',
    creators: [{ role: '글', name: '박태준만화회사' }, { role: '글', name: '땅콩' }, { role: '그림', name: '전선욱' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '토요일',
    startDate: '2024-01-08',
    endDate: '2025-02-28',
    nonExclusiveDate: '2028-02-28',
    episodeCount: 60,
    ageRating: '15+',
    mainGenre: '기타',
    keywords: [],
    element: '',
    logline: '',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'vs',
    title: 'VS',
    status: '완결',
    creators: [{ role: '글', name: '박태준만화회사' }, { role: '글', name: '한큰빛' }, { role: '그림', name: '한큰빛' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '목요일',
    startDate: '2024-01-24',
    endDate: '2025-05-21',
    nonExclusiveDate: '2028-05-20',
    episodeCount: 71,
    ageRating: '15+',
    mainGenre: '액션',
    subGenre: '느와르',
    keywords: ['도검액션', '가문싸움', '세력전'],
    element: '‘노량진’과 ‘마장동\' 시장 상인회의 생존권과 가문의 자존심을 건 도검 끝판대장!',
    logline: '시장 간의 긴 이권 다툼이 끝나고 노량진과 마장동 시장은 새로운 상인회가 출범했다.\n\n이제 주먹의 시대는 지난 걸까, 두 사람은 국회의원 만찬 자리에서 시장 경쟁을 펼친다.\n그러나 노량진의 고급 식자재를 실은 트럭이 괴한들에게 습격당하며 상황은 급변한다.\n\n서로를 향한 의심으로 잠들어 있던 갈등이 점화되어, 그들은 다시 주먹을 부딪치게 된다.\n과연 노량진과 마장동은 과거의 아픔을 반복할 것인가, 새로운 공존을 찾을 것인가?!',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'like-it-die',
    title: '좋아?죽어!',
    status: '완결',
    creators: [{ role: '글', name: '박태준만화회사' }, { role: '글', name: '김용키' }, { role: '그림', name: '죠' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '화요일',
    startDate: '2024-02-01',
    endDate: '2025-02-20',
    nonExclusiveDate: '2028-02-20',
    episodeCount: 113,
    ageRating: '18+',
    mainGenre: '스릴러',
    subGenre: '성인',
    keywords: ['스릴러', '범죄', '스토커', 'BJ', '삼각관계'],
    element: '부와 명성을 좇는 인터넷 BJ 민주. \n사랑, 집착, 그리고 공포가 뒤엉킨 치명적인 삼각관계에 갇히게 된다',
    logline: '민주는 남자들이 한번쯤 돌아볼 만큼 매력적인 외모의 인터넷 방송인으로 오직 유명세와 시청자 수만을 좇아 달려왔다. 그러나 어느 순간 두 개의 검은 그림자가 그녀의 삶을 서서히 파고든다.\n\n “서로 물어뜯다 죽여버려.” \n\n그녀는 결코 호락호락한 먹잇감이 될 수 없었다. 사랑과 집착, 그리고 위험이 뒤얽힌 긴장 속에서 세 청춘 남녀는 온라인과 현실의 경계를 넘나드는 서스펜스 로맨틱 스릴러를 만들어간다.',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'eat-fart-fight',
    title: '먹뀌싸',
    status: '완결',
    creators: [{ role: '글', name: '박태준만화회사' }, { role: '글', name: '김숭늉' }, { role: '그림', name: '팀숭늉' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '일요일',
    startDate: '2024-02-03',
    endDate: '2024-11-23',
    nonExclusiveDate: '2027-11-23',
    episodeCount: 45,
    ageRating: '15+',
    mainGenre: '판타지',
    subGenre: '액션',
    keywords: ['액션', '오컬트판타지', '동양판타지'],
    element: '요괴를 먹고, 뀌고, 싸운다!? 왕따 소년의 몸에 깃든 괴물 ‘먹귀사’가 세상에 나타난 지옥귀를 막기 위해 펼치는 개그 액션 배틀 판타지!',
    logline: '300년 동안 봉인돼 있던 정체불명의 존재 ‘지옥귀’가 세상에 풀려났다.\n\n그는 지옥문을 열어 인간계에 혼란을 일으키려 하고, 이를 막기 위해 나타난 존재가 있었으니—왜소한 왕따 소년 ‘오구영’의 몸에 깃든 ‘먹귀사’!요괴를 먹고 능력을 흡수하며 성장하는 이 괴이한 존재는 지옥귀에 맞서 인간계를 지키고자하는데...\n\n‘먹귀사\'는 과연 인간계를 지킬 수 있을 것인가?지금, 인간계와 지옥의 경계가 무너진다!',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'lumbini',
    title: '룸비니',
    status: '완결',
    creators: [{ role: '글', name: '박태준만화회사' }, { role: '그림', name: '약수' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '목요일',
    startDate: '2024-03-06',
    endDate: '2025-09-17',
    nonExclusiveDate: '2028-09-16',
    episodeCount: 67,
    ageRating: '15+',
    mainGenre: '미스테리',
    subGenre: '스릴러',
    keywords: ['오컬트', '사이비종교', '공포', '서스펜스', '복수', '빌런'],
    element: '낙원에서 태어난 괴물, 세상을 향해 복수를 시작한다!',
    logline: '결손이 있는 아이들을 위해 자애로운 자운스님과 선생님들이 세운 보금자리, ‘룸비니’.\n하지만 그들이 소속된 신흥종교 ‘일각교’의 수상한 종교활동과 거기서 들려오는기괴한 풍문으로 인해 일반인들의 발길이 끊긴 시설로 몰락했다.\n\n그리고 그곳에 유일하게 결손이 없는 아이, ‘영도’가 입소하게 된다. 자애로워 보였던 선생님들과 친구들에게 폭력과 학대를 당하던 영도. 간혹 따뜻함을 나누어 주던 이들이 있었으나, 결국 철저히 세뇌되어 룸비니 구성원들의 리더가 된다.\n\n자신들을 인신공양의 제물로 쓰려 했던 자운과 룸비니의 진실을 파헤치고,그간 핍박했던 모든 자들에게 복수를 감행하며 새로운 존재로 거듭나는 데...',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'delivery-king',
    title: '배달왕',
    status: '완결',
    creators: [{ role: '글', name: '박태준만화회사' }, { role: '그림', name: '박태준만화회사' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '목요일',
    startDate: '2024-04-20',
    endDate: '2025-12-03',
    nonExclusiveDate: '2028-12-02',
    episodeCount: 168,
    ageRating: '15+',
    mainGenre: '기타',
    keywords: ['일상', '드라마', '우정', '성장', '리얼리티'],
    element: '단 한 번의 배달 실수로 \n엉망이 된 한 사람의 인생',
    logline: '“내가 뭘 배달 한 거지?!“\n\n팍팍한 생활고를 벗어나기 위해 고액 배달알바를 한 후 감당할 수 없는 사건에 휘말리게 된 \'오기효\'. 어떻게든 살아남기위해 배달알바를 이어가고 자신이 일하는 배달업체에서 은퇴한 전설의 폭주족들을 만나게 된다.',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'law-of-boys',
    title: '소년법칙',
    status: '휴재',
    creators: [{ role: '글', name: '병장' }, { role: '글', name: '해태' }, { role: '그림', name: '호인' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '일요일',
    startDate: '2024-07-13',
    endDate: '2025-07-05',
    nonExclusiveDate: '2028-07-04',
    episodeCount: 52,
    ageRating: '15+',
    mainGenre: '액션',
    subGenre: '드라마',
    keywords: ['액션', '학원', '성장물', '스핀오프', '먼치킨'],
    element: '최강 킬러 육성소 데드맨션의 걸작 \'숀\'의 배틀 액션 활극!',
    logline: '비밀 보육원 데드맨션에서 최강의 킬러로 자란 숀은 사고로 인해 한국의 평범한 가정에 입양된다. 그 곳에서 평범한 삶을 살 수도 있었지만데드맨션의 회수 반에 의해 가족들이 모두 사망하고 혼자 살아 남은 숀은 힘과 기억을 잃은 채 살아간다. \n\n우연한 계기로 힘을 되찾은 숀을 다시 노리기 시작한 데드맨션, 그로부터 자신의 소중한 사람들을 지키고 기억을 되찾기 위한 숀의 전쟁이 시작된다.',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'love-in-body',
    title: '러브 인 바디',
    status: '완결',
    creators: [{ role: '글', name: '한요정' }, { role: '그림', name: '한요정' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '금요일',
    startDate: '2024-07-26',
    endDate: '2024-12-20',
    nonExclusiveDate: '2027-12-20',
    episodeCount: 36,
    ageRating: '12+',
    mainGenre: '기타',
    keywords: [],
    element: '',
    logline: '',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'find-the-crown',
    title: '왕관을 찾아줘',
    status: '완결',
    creators: [{ role: '글', name: 'MUTE' }, { role: '그림', name: 'MUTE' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '월요일',
    startDate: '2024-07-29',
    endDate: '2025-06-02',
    nonExclusiveDate: '2028-06-01',
    episodeCount: 45,
    ageRating: '15+',
    mainGenre: '판타지',
    subGenre: '로맨스',
    keywords: ['현대판타지', '동양풍로맨스', '운명', '전생', '저승사자'],
    element: '머리를 찾아야만 끝낼 수 있는 운명, 그리고 시작된 달콤하고 위험한 플러팅!',
    logline: '"너를 알아보는 이가 있다면 머리를 찾아 죗값을 치러라."\n\n얼굴이 존재하지 않은 상태로 태어난 저승사자 아리. 이승과 저승 어느 세계에서도 환영받지 못한 아리는 미친 듯한 외로움으로 살아올 수밖에 없었고 머리를 찾아 죄를 갚고 생을 마감하는 것이 아리의 최종 목표다.\n\n기나긴 시간 끝에 자신을 알아보는 이를 찾았지만, 상대는 자신과 정반대로 사랑을 받고 자란 톱스타 우철이었다. 머리를 찾아주는 조건으로 플러팅 해오는 우철을 아리는 감당해 낼 수 있을까?',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'daywalker',
    title: '데이워커',
    status: '연재중',
    creators: [{ role: '글', name: 'MUTE' }, { role: '그림', name: 'MUTE' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '토요일',
    startDate: '2024-08-02',
    endDate: '2025-10-10',
    episodeCount: 83,
    ageRating: '18+',
    mainGenre: '로맨스',
    subGenre: '성인',
    keywords: ['능력자배틀물', '시리어스', '범죄', '뱀파이어', '복수극'],
    element: '마약이라는 수위 높은 소재들의 적절한 조화로 자극적이지만 가볍고 빠른 속도감으로 볼 수 있는 남성향 작품!',
    logline: '"“보여주마. 네가 버린 개xx가 얼마나 사나웠는지.”\n\n토사구팽당한 국정원 블랙요원, 뱀파이어가 되어 복수에 나선다. 평생을 국가에 헌신한 블랙요원 김수혁. 임무를 나서지만 타깃은 고대 뱀파이어였고, 그대로 시쳇더미에서 생을 마감한 수혁은 뱀파이어로 부활했다. 복수 하기위해 뱀파이어 헌터 집단에 들어가 팀원들과 함께하게 된 \'뱀파이어\' 수혁. 그는 과연 결사대에서 살아남고 안나에게 복수를 할 수 있을 것인가?"',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'gun-gon-bul-i-gi',
    title: '건곤불이기',
    status: '연재중',
    creators: [
      { role: '글', name: '박태준만화회사' },
      { role: '글', name: '노경찬' },
      { role: '그림', name: '형1978' },
      { role: '원작', name: '임준욱' },
    ],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '수요일',
    startDate: '2024-08-20',
    episodeCount: 67,
    ageRating: '15+',
    mainGenre: '무협',
    keywords: [],
    element: '',
    logline: '건곤불이기乾坤不異記\n[하늘과 땅의 이야기는 다르지 않다.]\n\n신검神劍과 마도魔刀\n강호를 호령하는 두 고수.\n그중 마도魔刀의 무가 평범한 아이였던 \'반통미\'에게 이어진다.\n\n그저 바보처럼 성실하고 근면하기만한 아버지에게 불만을 가졌던 \'반통미\'.\n\n하지만 통미는 아버지가 얼마나 대단한 삶을 사는지 깨닫게 되고. 그 순간 마도는 빛을 발한다.',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'dog-deed',
    title: '개짓',
    status: '연재중',
    creators: [{ role: '글', name: '불사' }, { role: '그림', name: '서인화' }, { role: '원작', name: '김영한' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '일요일',
    startDate: '2024-10-26',
    episodeCount: 83,
    ageRating: '18+',
    mainGenre: '로맨스',
    subGenre: '성인',
    keywords: ['고수위', '오만남', '재벌남', '상처녀'],
    element: '강력한 정문그룹의 그늘 아래에서 영화당은 번성한다. 그러나 잔혹한 후계 전쟁에 휘말린 한 상속자가 그 안으로 발을 들이는 순간, 위험한 운명이 시작된다.',
    logline: '정문그룹의 둘째 며느리 민여진과 건설 대표이사 태언이 영화당을 찾으며 사희의 삶은 흔들린다. \n\n태언의 노골적인 시선에 불편함을 느끼던 사희는 자주 마주치며 점차 그에게 끌리고, 결국 태언의 직설적인 접근으로 육체적인 관계를 맺는다. \n\n하지만 감정은 감춘 채 애매한 관계를 이어간다. 사희는 점차 태언에 대한 자신의 마음을 깨닫고 그를 떠나려 하지만, 이를 눈치챈 태언은 그녀를 붙잡기 위해 행동에 나선다. 마침내 사희를 괴롭히던 일가가 몰락하고, 태언과 사희는 함께 살기로 한다.',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'guryong-saroka',
    title: '구룡: 사로카',
    status: '완결',
    creators: [{ role: '글', name: '박태준만화회사' }, { role: '글', name: '백인휘' }, { role: '그림', name: '백인휘' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '월요일',
    startDate: '2024-10-28',
    endDate: '2026-03-09',
    nonExclusiveDate: '2029-03-08',
    episodeCount: 65,
    ageRating: '15+',
    mainGenre: '액션',
    subGenre: '느와르',
    keywords: ['캐슬', '스핀오프', '액션'],
    element: '',
    logline: '유일한 혈육인 동생을 찾기 위해 킬러가 된 서진태. 수소문 끝에 동생의 행방이 홍콩 최대 범죄조직 삼합회와 관련돼 있다는 것을 알게 되고 무작정 홍콩으로 향하는데...',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'night-visitor',
    title: '밤의 방문자',
    status: '완결',
    creators: [{ role: '글', name: 'MUTE' }, { role: '글', name: '리브바이' }, { role: '그림', name: 'MUTE' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '수요일',
    startDate: '2024-10-30',
    endDate: '2025-11-26',
    nonExclusiveDate: '2028-11-25',
    episodeCount: 72,
    ageRating: '18+',
    mainGenre: '로맨스',
    subGenre: '성인',
    keywords: ['소설원작', '성인웹툰', '기억상실', '운명'],
    element: '밤마다 찾아오는, 그 남자는 누구일까? \n잃어버렸던 운명의 상대를 찾게 되는 고자극 현대 드라마',
    logline: '4년 전 다섯 달의 기억을 잃고 아이를 낳게 된 세연은 얼굴이 보이지 않는 남자와 사랑을 나누는 꿈을 꾼다.\n\n 생생한 감각에 세연은 그 남자를 궁금해하고 풀리지 않는 궁금증을 갖고 지내던 어느 날 아버지의 주치의로 미국에서 온 수혁을 보며 알 수 없는 아련함과 낯익은 그리움을 느끼게 되는데...',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'high-class',
    title: '하이클래스',
    status: '연재중',
    creators: [{ role: '글', name: '박태준만화회사' }, { role: '글', name: '르티' }, { role: '그림', name: '르티' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '목요일',
    startDate: '2024-10-30',
    episodeCount: 66,
    ageRating: '15+',
    mainGenre: '액션',
    subGenre: '학원',
    keywords: [],
    element: '',
    logline: '고향을 떠나 무작정 서울로 상경한 왕담. 정착 자금을 받기 위해선 전교 1등을 해야 한다! 그런데 하필 전학 갈 학교가 공부만 하면 방해하는 최악들만 모인 일명 \'빡고\'였는데... 과연 왕담은 최악의 환경에서 전교 1등을 할 수 있을까?',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'desire-diary-deep',
    title: '욕망일기DEEP',
    status: '완결',
    creators: [{ role: '글', name: '박태준만화회사' }, { role: '글', name: '김꿀빨' }, { role: '그림', name: '누리마루' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '월요일',
    startDate: '2024-11-06',
    endDate: '2025-05-26',
    nonExclusiveDate: '2028-05-25',
    episodeCount: 161,
    ageRating: '15+',
    mainGenre: '스릴러',
    subGenre: '미스터리',
    keywords: ['옴니버스', '고자극'],
    element: '',
    logline: '더욱 더 매운맛으로 돌아온 욕망일기의 새로운 에피소드 인간이라면 누구나 가질법한 욕망, 그것이 현실로 이루어진다면? 그 끝은 과연 행복일까 파멸일까..',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'vantablack',
    title: '벤타블랙',
    status: '완결',
    creators: [{ role: '글', name: 'MAJOR' }, { role: '글', name: '신신성' }, { role: '그림', name: '신신성' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '일요일',
    startDate: '2024-11-10',
    endDate: '2025-10-26',
    nonExclusiveDate: '2028-10-25',
    episodeCount: 50,
    ageRating: '15+',
    mainGenre: '기타',
    keywords: [],
    element: '',
    logline: '',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'justice-realized',
    title: '정의구현',
    status: '완결',
    creators: [{ role: '글', name: 'MAJOR' }, { role: '글', name: '이시현' }, { role: '그림', name: '이시현' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '목요일',
    startDate: '2024-11-20',
    endDate: '2026-02-18',
    nonExclusiveDate: '2029-02-17',
    episodeCount: 55,
    ageRating: '15+',
    mainGenre: '액션',
    subGenre: '드라마',
    keywords: ['범죄', '참교육', '사이다', '히어로', '눈눈이이'],
    element: '눈에는 눈 이에는 이, 저지른 범죄만큼 처벌한다!',
    logline: '사랑하는 아내를 유린한 강도들을 왜 감옥에 가둬놓아야 할까?\n내 아내에게 그랬듯, 그들도 똑같은 고통을 느껴야 하는 거잖아…!’\n\n아내를 살해한 강도들을 맨손으로 때려죽인 전직군인 김태필.  한 평생을 국민을 지키는 데 힘썼지만 정작 이 나라는, 법은 태필을 지켜주지 않았고\n태필의 행동을 과잉 대응이라 판결, 살인범으로 만들어버린다. \n\n모든 걸 잃고 무력감에 빠진 채 감옥에서 썩어 가던 그런 그에게 국회의원 시진수가 찾아오고 태필에게 뜻밖의 제안을 해오는데...\n "김태필 씨, 처벌자가 되어주십시오."\n\n정의를 잃은 법위에 새로운 질서를 세우려는,초법적 권한을 가진 국가공인 처벌자 10인의 통쾌한 공적 복수극!',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'worst-generation',
    title: '최악의 세대',
    status: '완결',
    creators: [
      { role: '글', name: 'MAJOR' },
      { role: '글', name: '광산' },
      { role: '그림', name: 'MAJOR' },
      { role: '그림', name: '광산' },
    ],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '월요일',
    startDate: '2024-11-24',
    endDate: '2026-03-22',
    nonExclusiveDate: '2029-03-21',
    episodeCount: 54,
    ageRating: '15+',
    mainGenre: '액션',
    subGenre: '느와르',
    keywords: ['MZ조폭', '사이다', '카타르시스', '참교육'],
    element: 'MZ조폭 VS 낭만건달 현 시대의 세대갈등을 화끈한 느와르 액션물!',
    logline: '과거 시대를 풍미한 전설의 주먹, 정불도.\n\n오랜 수감 끝에 출소한 뒤 새 인생을 살아가려 하지만, 봉사활동 중 인연을 맺은 한 여고생이 사라지며 불길한 예감을 느낀다.\n\n고민 끝에 찾아간 여고생의 집에서 과거의 동료를 만나게 되고. 동료의 아이였던 여고생이 소위 \'MZ조폭\'이라 불리는 쓰레기들에게 해코지를 당했다는 이야기를 들은 정불도의 분노는 하늘을 찌르게 된다.\n\n자신의 주변인을 건드린 이들을 가만 두지 않겠다며 MZ조폭이 운영하는 클럽들을 모조리 박살내는 정불도를 흥미롭게 지켜보던 \'태은석\'은 자신의 복수에 불도를 이용하려 하는데...',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'namje',
    title: '남제',
    status: '완결',
    creators: [{ role: '글', name: 'MAJOR' }, { role: '글', name: '윤영일' }, { role: '그림', name: '윤영일' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '수요일',
    startDate: '2024-12-10',
    endDate: '2026-04-07',
    nonExclusiveDate: '2029-04-06',
    episodeCount: 51,
    ageRating: '15+',
    mainGenre: '액션',
    subGenre: '느와르',
    keywords: ['박투', '세력전', '배틀', '서바이벌', '클리셰박살'],
    element: '다양한 군상 속 컨셉별 토너먼트 배틀을 갖춘 무차별 박투 액션! 클리셰를 비튼 전개를 통한 통쾌한 남성향 낭만 서사와 화끈한 액션 카타르시스 선사할 작품!',
    logline: '주먹 인생을 건 남자들의 축제(男祭)!\n\n과거 정부에서 실시한 범죄와의 전쟁은 실패로 돌아가고 세상은 주먹들의 아비규환이 된다. \n\n이 지옥을 일통한 기업형 조폭 태진 그룹회장 \'진영의\'. 그는 자신의 사후 태진의 모든 것을 물려줄 후계자를 찾기 위하여 오직 자신의 힘과 실력 만으로 겨루는 진짜 남자들의 축제, \'남제\'를 개최한다.\n\n우연히 이 \'남제\'에 초대받은 청년백수건달 \'강대오\'는 자신의 주먹으로 태진 그룹을 쟁취하고 피라미드의 정점에 서기 위해 전국에서 몰려든 괴물 같은 초강자들과 생존을 건 혈투를 시작한다.',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'myeongwang',
    title: '명왕',
    status: '완결',
    creators: [{ role: '글', name: 'MAJOR' }, { role: '글', name: '금기혁' }, { role: '그림', name: '금기혁' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '토요일',
    startDate: '2024-12-27',
    endDate: '2025-12-05',
    nonExclusiveDate: '2028-12-04',
    episodeCount: 50,
    ageRating: '15+',
    mainGenre: '기타',
    keywords: [],
    element: '',
    logline: '',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'frozen-warrior',
    title: '냉동무사',
    status: '연재중',
    creators: [
      { role: '글', name: '박태준만화회사' },
      { role: '글', name: '토이' },
      { role: '글', name: '서행해주십시오' },
      { role: '그림', name: '최용준' },
    ],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '일요일',
    startDate: '2025-02-08',
    endDate: '2026-01-17',
    nonExclusiveDate: '2029-01-16',
    episodeCount: 42,
    ageRating: '15+',
    mainGenre: '기타',
    keywords: [],
    element: '',
    logline: '',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'killing-field',
    title: '킬링필드',
    status: '완결',
    creators: [{ role: '글', name: 'MAJOR' }, { role: '글', name: '012' }, { role: '그림', name: '012' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    startDate: '2025-02-10',
    endDate: '2025-11-10',
    nonExclusiveDate: '2028-11-09',
    episodeCount: 40,
    ageRating: '18+',
    mainGenre: '기타',
    keywords: ['액션', '생존게임', '음모', '가족', '드라마', '배틀'],
    element: '죽기 전에는 \n절대 빠져나갈 수 없다',
    logline: '은퇴를 하고 과거 보육원에서 가족처럼 지낸 동생 구상혁의 카페에서\n정체를 숨긴 채 살아가던 킬러 정도균.\n\n어느 날, 상혁이 갑자기 사라지고 정도균은 상혁의 흔적 쫒아\n상혁이 납치된 정체불명의 섬에 발을 들인다.\n\n그리고 그곳에서, 도균은 납치 된 채 노예처럼 일하고 있는 사람들과\n그들을 감시하는 킬러들을 마주하게 된다.\n설상가상으로 도균은 자신의 가족을 살해한 킬러가 섬에 있다는 것을 알게 되는데...!\n\n복수를 결심한 도균과 무자비한 킬러들의 목숨을 건 전쟁이 시작된다!',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'suit-flex',
    title: '수트빨',
    status: '완결',
    creators: [{ role: '글', name: '김꿀빨' }, { role: '그림', name: '이세형' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '목요일',
    startDate: '2025-04-02',
    endDate: '2025-12-10',
    nonExclusiveDate: '2028-12-09',
    episodeCount: 32,
    ageRating: '15+',
    mainGenre: '기타',
    keywords: [],
    element: '',
    logline: '',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'forced-assembly',
    title: '강제소집',
    status: '완결',
    creators: [{ role: '글', name: '남자의이야기' }, { role: '그림', name: 'GArt' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '수요일',
    startDate: '2025-04-22',
    endDate: '2026-01-27',
    nonExclusiveDate: '2029-01-26',
    episodeCount: 34,
    ageRating: '18+',
    mainGenre: '스릴러',
    subGenre: '액션',
    keywords: ['액션', '생존게임', '여성서사', '가족'],
    element: '정체불명의 서바이벌 게임에 끌려온 박윤정, 규칙은 단 하나. 살아남지 못하면 끝이다.',
    logline: '120명의 참가자가 강제로 끌려와 벌이는 생존 배틀로얄, ‘강제소집’. \n\n주인공은 어느 날 뜻하지 않게 징병 게임에 소환되어 배신과 공포, 함정이 난무하는 무대에 던져진다. 엄마의 배신과 죽음을 목격하며 절망했지만, 진실은 달랐다. 엄마는 딸을 살리기 위해 자신을 희생했던 것이다. \n\n딸은 다시 기회를 얻어 1년간 철저히 준비해 두 번째 게임에 참여한다. 게임의 룰을 분석하고 약점을 파고든 끝에 모든 라운드를 돌파하며 엄마의 부활에 대한 실마리에 다가서지만, 이 비극적인 서바이벌은 단순한 게임이 아닌 사회적 제도로 굳어져가며 감춰져 있던 진실이 밝혀지게 된다.',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'level-999-goblin',
    title: '레벨 999고블린',
    status: '연재중',
    creators: [{ role: '글', name: '다피' }, { role: '그림', name: '곰곰' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '화요일',
    startDate: '2025-05-12',
    episodeCount: 25,
    ageRating: '15+',
    mainGenre: '판타지',
    subGenre: '코미디',
    keywords: ['게임판타지', '액션배틀'],
    element: '인생은 한방?! 레벨999 고블린으로 인생역전!',
    logline: '남들보다 부족한 외모, 부족한 능력으로 노가다로 생계를 유지하는 주인공 김철수! 가상현실 게임 ‘헤븐스 도어’를 통해 돈을 벌 수 있다는 소문을 듣고 현실도피하듯 게임을 시작한다.\n\n게임 속 히든던전에서 생애 처음으로 ‘히든 클래스’라는 직업을 얻는 기회를 잡았으나, 전직한 직업은 하필 고블린 소환사. 실망도 잠시, 소환한 고블린이 무려 레벨 999의 만렙 고블린이었고 그 덕분에 하루가 멀다 하고 사건 사고에 휘말리게 된다. 한편 같은 히든 던전에서 게임을 플레이하던 대한민국 재벌그룹 ‘세명그룹’ 회장 ‘한기문’의 딸 ‘캐서린’은 몬스터 가이거의 공격을 받고 게임 속 충격이 현실의 정신적 충격으로 이어지는 이른바 ‘리타이어 쇼크’ 로 현실세계에서 혼수 상태에 빠진다. 어쩔 수 없이 김철수는 캐서린의 회복을 돕기위한 여정에 휘말리게 된다.\n\n그러던 와중, 사실 ‘헤븐스 도어’는 세계 정부가 인구 조절을 위해 만든 생존 게임인 것을 알게되며 게임 유저들은 살기 위해 자연스럽게 강자들 주위로 모이게 되고 강자 중에 강자가 된 김철수는 원치 않는 운명 속에서 사람들을 구하고 영웅으로 추앙받는 ‘어쩌다 영웅’이 되어 가는데…',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'twelve-zodiac-girl',
    title: '십이지소녀',
    status: '연재중',
    creators: [{ role: '글', name: 'MAJOR' }, { role: '글', name: '지지' }, { role: '그림', name: '지지' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '월요일',
    startDate: '2025-06-29',
    episodeCount: 25,
    ageRating: '15+',
    mainGenre: '판타지',
    subGenre: '로맨스',
    keywords: ['학원판타지', '하렘', '미소녀', '이능력', '성장', '십이지'],
    element: '십이지 신에 빙의 된 소녀들을 구해야 한다! 유쾌하고 러블리한 본격 초능력 판타지 소녀 액션 작품!',
    logline: '과거 십이지 신을 정하는 시합에서 13위로 순위에 들지 못한 고양이 니나!\n\n몇 천년 후, 니나는 십이지 신에 들고 싶어 십이지 신을 정하는 사합을 다시 개최해버리고  시합의 힘에 의해 본래 하늘에 있었어야할 열두 신이 세상에 강림하게 된다.\n\n그리고 불가항력으로 시합의 심판으로 지정 되 열두 신을 게임에 참가시켜야 하는평범한 고등학생 이우주, 그런데 열두 신이 우주의 주변 소녀들에게 강림했다고?!\n\n하늘의 신령계에 있는 신들은 인간이사는 지상에 내려올 때 본체가 내려올 수 없기에 ‘주신자’라는 인간에게 빙의해서 활동을 해야 하는데 ‘주신자’가 된 소녀들은  ‘주신자’라는 인간에게 빙의해서 활동을 해야 하는데 ‘주신자’가 된 소녀들은 신의 힘을 이용해 자신의 욕망을 실현하기 시작하는데...',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'hero-life-record',
    title: '용사생활기록부',
    status: '연재중',
    creators: [{ role: '글', name: '땅콩' }, { role: '그림', name: '땅콩' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '일요일',
    startDate: '2025-07-05',
    episodeCount: 23,
    ageRating: '15+',
    mainGenre: '코미디',
    subGenre: '판타지',
    keywords: ['개그', '학원물'],
    element: '대한민국 서울의 어느 고등학교. 이곳에 용사와 마법사, 엘프가 있다?! 평범한 고등학생 \'윤희원\'과 예측불가능한 용사의 동료들이 펼치는 좌충우돌 대한민국 생존기!',
    logline: '어디에나 있을 법한 평범한 고등학생, 윤희원. \n\n어느 날, 마법사 ‘그리모어’의 환생인 마소희가 전학생으로 등장하고 그는 사실, 과거에 마왕을 물리쳤던 전설의 용사의 환생임을 알게 된다. \n\n주인공은 마소희(그리모어의 환생)와 흩어진 동료들의 환생을 찾아 나서며 현실 세계에서 모습을 감추고 있는 마왕을 다시 쓰러뜨리고자 하는데…',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'taejeon-biroku',
    title: '태존비록',
    status: '연재중',
    creators: [{ role: '글', name: '김꿀빨' }, { role: '그림', name: '레드훅' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '일요일',
    startDate: '2025-07-12',
    episodeCount: 21,
    ageRating: '15+',
    mainGenre: '무협',
    subGenre: '액션',
    keywords: ['무협', '먼치킨', '액션'],
    element: '게으름뱅이 인간말종이였던 위연호가 진정한 대협 ‘광휘무존’으로 거듭나는 이야기',
    logline: '광휘무존(光輝武尊), 천하의 겁란을 종식시킨 위대한 대협, 위연호!\n\n우리는 그를 군자, 그리고 대협이라 불렀지만 사실 그는 완전 인간 말종이라 불릴 만큼 차마 세상에 알릴 수 없는 진실을 감추고 있었다!?! \n\n하루 8시간만 자고 싶은 그는 뜻밖의 기연을 얻고 단숨에 초고수의 반열에 오르게 되는데...그러나 특이하게도 그는 다시 게으름뱅이로 돌아가 세상을 유유히 떠도는 삶을 선택한다.',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'evil-spirit-rakshasa',
    title: '악귀나찰',
    status: '연재중',
    creators: [{ role: '글', name: '김숭늉' }, { role: '그림', name: '김구름' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '목요일',
    startDate: '2025-08-13',
    episodeCount: 20,
    ageRating: '15+',
    mainGenre: '판타지',
    subGenre: '액션',
    keywords: ['오컬트판타지', '동양판타지', '느와르', '스릴러'],
    element: '건달 홍도진, 요괴의 힘을 빌려 복수를 행하다!',
    logline: '수백 년 전, 아내와 딸, 가문을 잃고 갑급요괴 나찰과 계약했으나 스스로 목숨을 끊어 계약을 막아낸 진강, 하지만 그 피의 계약은 아직 끝나지 않았고, 현대에 건달로 살아가는 홍도진의 몸에 깃들며 다시 깨어난다. \n\n사람을 죽일수록 강해지는 요괴의 힘을 손에 쥔 그는 복수를 이어가지만 인간의 영혼을 지키려는 의지와 악귀로 완전히 잠식되려는 욕망 사이에서 끝없는 갈등에 휘말리게 되는데...요괴와의 금단의 계약이 만들어낸 동양풍 오컬트 판타지!',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'oh-my-guru',
    title: '오나의교주님',
    status: '연재중',
    creators: [{ role: '글', name: '김꿀빨' }, { role: '그림', name: '김완두' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '화요일',
    startDate: '2025-08-14',
    episodeCount: 28,
    ageRating: '18+',
    mainGenre: '스릴러',
    subGenre: '드라마',
    keywords: ['사이비', '스릴러', '복수극'],
    element: '사이비에게 빼앗긴 가족, 되찾을 수 없는 삶… 오직 복수만이 남았다!',
    logline: '“오, 나의 교주님. 제가 보내드릴게요. 그토록 좋아하시는… 주님 곁으로.”\n\n사이비 종교 ‘진천교’에서 태어나 부모마저 교단에 몸담으며 살아온 한성민. 그러나 교주의 탐욕과 욕망은 결국 그의 가족을 파탄 내고, 모든 것을 잃은 그는 홀로 탈출한다. \n\n수년 뒤 성인이 된 성민은 다시 교단에 잠입해, 자신을 파멸시킨 교주에게 치밀하고 처절한 복수를 시작한다!',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'off-work-today',
    title: '오늘도 퇴근',
    status: '연재중',
    creators: [
      { role: '글', name: '파셔' },
      { role: '글', name: '백초' },
      { role: '그림', name: '물속' },
      { role: '원작', name: '피셔' },
    ],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '화요일',
    startDate: '2025-09-16',
    episodeCount: 15,
    ageRating: '12+',
    mainGenre: '드라마',
    keywords: ['오피스', '소설원작', '힐링'],
    element: '',
    logline: '한국 굴지의 대기업 소야그룹 ESG팀의 팀장 이민수!\n그는 오늘도 칼퇴근을 목표로 묵묵히 일을 한다.\n\n어느 날, 회장의 막내딸 강채은이 팀원으로 들어오게 되면서\n회사 정치에 엮여 사내 빌런들과 부딪치며 다양한 사건을 겪게 되는데…\n\n이민수는 과연 칼퇴근을 할 수 있을까?',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'night-friend',
    title: '밤친구',
    status: '연재중',
    creators: [{ role: '글', name: 'MUTE' }, { role: '그림', name: 'MUTE' }, { role: '원작', name: '리브 바이' }],
    platform: '네이버웹툰',
    serialType: '매일+',
    dayOfWeek: '금요일',
    startDate: '2025-10-09',
    episodeCount: 13,
    ageRating: '18+',
    mainGenre: '로맨스',
    subGenre: '드라마',
    keywords: ['소설원작', '오피스', '로맨스', '성인'],
    element: '밤에만 만나는 뜨거운 파트너를 \n낮에 회사에서 마주치다!? \n\n아찔하고 은밀한 사내 로맨스.',
    logline: '나에게는 밤에만 만나는 특별한 친구가 있다. 이름도, 나이도, 연락처도 모른 채 오직 빚어낸 듯 잘생긴 얼굴과 아찔한 쾌락만을 공유하는 \'밤친구\'.\n\n그와 위험하고도 달콤한 관계를 맺어온 지 한 달이 되던 어느 날, 평범한 일상을 보내던 나의 앞에 그가 나타났다. 밤이 아닌 낮에, 그것도 바로 내가 다니는 회사에서!',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'between-two-mens-secretary',
    title: '두 남자의 비서 사이',
    status: '연재중',
    creators: [
      { role: '글', name: '이달아' },
      { role: '글', name: '불사' },
      { role: '그림', name: '바둑이' },
      { role: '원작', name: '이달아' },
    ],
    platform: '네이버웹툰',
    serialType: '매일+',
    dayOfWeek: '토요일',
    startDate: '2025-12-05',
    episodeCount: 0,
    ageRating: '18+',
    mainGenre: '로맨스',
    subGenre: '성인',
    keywords: ['오피스로맨스', '계약관계', '계략남', '집착남'],
    element: '믿었던 남자의 배신, 그리고 그의 친구와의 계약결혼...복수를 향한 그녀의 반격의 시작!',
    logline: '어린 시절 자신의 곁을 지켜주던 한태민과의 결혼 약속을 믿으며 오랜시간 그의 곁을 지킨 공주희. \n\n하지만 태민은 자신의 성공을 위해 주희를 괴롭혔던 혜나와의 결혼을 선택한다. 주희는 복수를 결심하고 태민의 친구이자 직장 상사인 유제하에게 계약결혼을 제안하고, 오래전부터 주희를 짝사랑하던 제하는 그녀의 복수를 돕기 위해 흔쾌히 제안을 받아드리는데...',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'bloodrain-3',
    title: '블러드레인3',
    status: '연재중',
    creators: [{ role: '글', name: 'MAJOR' }, { role: '글', name: '백두' }, { role: '그림', name: '백두' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '화요일',
    startDate: '2025-12-15',
    episodeCount: 0,
    ageRating: '15+',
    mainGenre: '액션',
    subGenre: '느와르',
    keywords: ['액션', '느와르'],
    element: '',
    logline: '한국 느와르 액션의 전설, <블러드레인>의 최종장! 대한민국 역대급 폭력 조직 서양의 대보스 \'이정우\'. 긴 우여곡절 끝에 바라던 일상을 찾았지만 균열이 시작됨을 깨닫는다. 한편, 마약 범죄 검거를 위하여 투입된 형사 \'강혁\'은 그 끝에 서양이 있다는 것을 알게 되고 이정우를 쫓게 되는데.. 천외천 \'이정우\', 그를 처단하기 위한 \'강혁\'.',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'princess-goes-to-school',
    title: '공주님 학교 가신다',
    status: '연재중',
    creators: [{ role: '글', name: 'MUTE' }, { role: '그림', name: 'MUTE' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '금요일',
    startDate: '2025-12-18',
    episodeCount: 0,
    ageRating: '15+',
    mainGenre: '개그',
    subGenre: '로맨스',
    keywords: [],
    element: '',
    logline: '북한의 차기 지도자 후보이자 공주님 김설. 그러나 김설은 자신이 김정운의 딸인 걸 모른채 평범한 대한민국의 고등학생으로 살아가고 있다. 그런 그녀의 일상을 지키기 위해 최연소 블랙 요원 \'정수현\'이 고등학교로 투입 되며 벌어지는 학원 로맨스 코미디!',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'royal-family',
    title: '로열패밀리',
    status: '연재중',
    creators: [{ role: '글', name: 'MAJOR' }, { role: '그림', name: '옥한돌' }, { role: '원작', name: '십오기' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '수요일',
    startDate: '2025-12-23',
    episodeCount: 0,
    ageRating: '15+',
    mainGenre: '드라마',
    subGenre: '액션',
    keywords: ['액션', '느와르', '정치', '소설원작'],
    element: '',
    logline: '대한민국 최대 재벌 \'태성\'의 장손 강지혁. 태성의 모든 것을 물려받았어야 하지만 누군가의 음모로 인해 부모님을 잃고 고아원에 버려지게 되는데... 20여년의 세월이 흘러 \'서지혁\'이란 이름으로 태성으로 돌아온 그의 복수가 시작된다.',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'cheerful-god',
    title: '유쾌한 신',
    status: '연재중',
    creators: [{ role: '글', name: '외눈박이' }, { role: '글', name: '김숭늉' }, { role: '그림', name: '김용키' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '수요일',
    startDate: '2025-12-27',
    episodeCount: 0,
    ageRating: '18+',
    mainGenre: '스릴러',
    subGenre: '드라마',
    keywords: ['아포칼립스', '컷툰'],
    element: '',
    logline: '지진으로 모든 것이 무너져버린 세상. 사이코패스 아버지를 확인하려는 소녀와 그를 쫓는 남자. 그리고 신처럼 추앙받는 살인자의 이야기.',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'taxidermy',
    title: '박제',
    status: '연재중',
    creators: [{ role: '글', name: 'MUTE' }, { role: '그림', name: '임송' }, { role: '원작', name: '승하' }],
    platform: '네이버웹툰',
    serialType: '매일+',
    dayOfWeek: '금요일',
    startDate: '2026-01-08',
    episodeCount: 0,
    ageRating: '18+',
    mainGenre: '로맨스',
    subGenre: '드라마',
    keywords: ['소설원작', '로맨스', '성인'],
    element: '',
    logline: '“저 이묘진은 태정환 의원님 댁을 위해 태어났습니다.” \n\n국토부장관 태정환이 한 집안의 선산을 파헤친 탓에 동티가 났다. \n집안의 장손 태유강을 지키기 위해 액받이 여자아이를 산속 사윤당에 숨어 키운다. \n\n“네가 싫든 좋든 난 이 지옥 같은 곳에서 널 꺼낼 테니까.”',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'ovcharka',
    title: '오브차카',
    status: '연재중',
    creators: [{ role: '글', name: '해태' }, { role: '그림', name: '박태준만화회사' }, { role: '그림', name: '병장' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '토요일',
    startDate: '2026-01-16',
    episodeCount: 0,
    ageRating: '15+',
    mainGenre: '액션',
    subGenre: '느와르',
    keywords: ['복수', '백XX스핀오프'],
    element: '',
    logline: '러시아 마피아 빅 보스의 피습. 권력을 노린 배신이 조직을 무너뜨린다. 오브차카 보리스는 친우의 피 앞에서 복수를 선택한다.',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'director-needs-one-more-night',
    title: '전무님은 하룻밤이 부족하다',
    status: '연재중',
    creators: [
      { role: '글', name: '한여름이었다' },
      { role: '글', name: '횡초' },
      { role: '그림', name: '악고' },
      { role: '원작', name: '한여름이었다' },
    ],
    platform: '네이버웹툰',
    serialType: '매일+',
    dayOfWeek: '월요일',
    startDate: '2026-01-18',
    episodeCount: 0,
    ageRating: '18+',
    mainGenre: '로맨스',
    subGenre: '드라마',
    keywords: ['소설원작', '오피스로맨스', '시한부'],
    element: '',
    logline: '남자친구가 아끼는 후배와 바람이 났다. 아이까지 가진 채로... \n\n거기에 난데없이 1년 시한부 판정을 받은 노해원은 이제부터 요부처럼 살겠다고 다짐하고 버킷리스트를 만든다. \n\n평소 그녀를 마음에 두고 있던 상사 강태경은 우연히 그녀의 버킷리스트를 보게 되고 버킷리스트 인‘결혼하기’를 이뤄주기 위해 계약결혼을 제안하는데...',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'crime-city-zero',
    title: '범죄도시 제로',
    status: '연재중',
    creators: [],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '일요일',
    startDate: '2026-02-14',
    episodeCount: 0,
    ageRating: '15+',
    mainGenre: '액션',
    subGenre: '개그',
    keywords: ['영화원작웹툰'],
    element: '',
    logline: '통쾌하게 싹 쓸어버린다! 괴물형사 마석도의 초보 시절!\n\n최악,최강의 조폭을 소탕하기 위한 은밀한 작전이 시작된다!\n영화 <범죄도시> 시리즈의 공식 프리퀄 웹툰',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'shepherd-wizard',
    title: '양치기 마법사',
    status: '연재중',
    creators: [
      { role: '글', name: '박태준만화회사' },
      { role: '글', name: '김꿀빨' },
      { role: '그림', name: 'YU' },
      { role: '원작', name: '수박복숭아' },
    ],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '화요일',
    startDate: '2026-02-23',
    episodeCount: 0,
    ageRating: '15+',
    mainGenre: '판타지',
    keywords: ['먼치킨', '성장물', '소설원작'],
    element: '',
    logline: '세계의 운명을 뒤흔들 다크&하이 판타지 대서사시!\n\n어머니의 가르침에 따라 힘을 숨긴 채 양을 치며 유유자적한 삶을 살아가는 양치기 투란! 그는 우연히 마을에 들이닥친 마수와 마수를 처치하러 온 기사 케오른과의 인연으로 언덕 밖의 \'세상\'에 관심을 갖게 된다.\n\n자신을 서쪽 끝의 평범한 마을에 양치기로 키울 수 밖에 없었던 부모님의 흔적을 찾기위해 세상 밖으로 긴 여행을 떠나게 된 그. 여행을 거듭하며 수 많은 사람과 여러 도시와 대가문을 겪게 되고, 점차 세상을 뒤 흔들게 될 프레아 신족의 숨겨진 비밀과 마주하게 된다.',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'no-what-if',
    title: '만약은 없다',
    status: '준비중',
    creators: [
      { role: '글', name: '남궁인' },
      { role: '글', name: '시니' },
      { role: '그림', name: '본인(김동렬)' },
      { role: '원작', name: '남궁인' },
    ],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    startDate: '',
    episodeCount: 0,
    ageRating: '전체',
    mainGenre: '드라마',
    subGenre: '의학',
    keywords: ['응급실', '의학', '드라마', '리얼리티'],
    element: '죽음과 삶 그 경계에서의 아슬아슬한 줄타기!',
    logline: '수만 명의 환자와 수 천명의 자살자, 수백 구의 시신을 만나는 일이 일상인 응급실. 그 곳에서 매일 같이 수많은 생명을 마주하는 응급의학과 의사 정궁인은 죽음 앞에서도 끝까지 최선을 다해야 한다는 강박적인 책임감을 안고 살아간다.\n\n응급실에서 매 순간 펼쳐지는 죽음의 장면과 그로 인해 흔들리는 인간의내면을 생생히 담아내어 죽음과 삶을 바라보는 새로운 인식을 독자에게 전한다.',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'stray-bullet',
    title: '스트레이불렛',
    status: '준비중',
    creators: [],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    startDate: '',
    episodeCount: 0,
    ageRating: '전체',
    mainGenre: '드라마',
    subGenre: '느와르',
    keywords: ['조폭', '브로맨스', '언더커버', '복수', '배신'],
    element: '브로맨스 기반의 현대와 레트로가 섞인 다채로운 액션의 B급 느와르 작품!',
    logline: '제멋대로인 에덴상사 에이스 킬러 이태이는 상대 조직을 전멸시키는 도중 흙감자 같은 신입 김은호를 후임으로 맞이 한다.\n\n사실 어리바리한 잠입 경찰이었던 김은호는 태이와 많은 시간을 보내면서 경찰과 조직 사이에서 갈등하기 시작하고 결국 태이를 제거하기로 마음먹는데...',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'young-wife-bad-deeds',
    title: '어린 아내와 나쁜 짓',
    status: '준비중',
    creators: [
      { role: '글', name: '이리와' },
      { role: '글', name: '무멘' },
      { role: '그림', name: '황유승' },
      { role: '원작', name: '이리와' },
    ],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    startDate: '',
    episodeCount: 0,
    ageRating: '전체',
    mainGenre: '로맨스',
    subGenre: '드라마',
    keywords: ['나이차커플', '직진남', '재벌', '상처녀', '소설원작'],
    element: '첫사랑이었던 나의 구원자가\n맹렬하게 집착하는 남편이 되어 돌아왔다.',
    logline: '피도 눈물도 없는 무뢰배이자 국내 최대 폭력 조적의 후계자 범도건.\n그는 어린 시절 궁핍했던 천애 고아 서이재에게 유일하게 손길을 내밀어준\n어른이자 첫사랑이었다.\n\n시간이 지나 다시 만난 두 사람.\n도건은 도망칠 기회를 주었지만 이재는 이를 거절한 채 \n3년짜리 계약결혼을 제안한다.\n\n세상에서 가장 완벽하고 위험한 남자에게 자신은 그저 \n초라한 가짜 아내라고 생각하며...',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'nis-junior-agent',
    title: '국정원 말단직원',
    status: '연재중',
    creators: [{ role: '글', name: 'MUTE' }, { role: '그림', name: 'MUTE' }, { role: '원작', name: '삼툴' }],
    platform: '네이버웹툰',
    serialType: '요일웹툰',
    dayOfWeek: '목요일',
    startDate: '2026-02-11',
    episodeCount: 0,
    ageRating: '12+',
    mainGenre: '액션',
    subGenre: '개그',
    keywords: ['범죄', '소설원작'],
    element: '',
    logline: '시험 없이 7급 공무원 되는 개꿀팁! \n추천으로 군 복무 중 \'국정원 특채\'되기..! \n\n그렇게 난 세계의 화약고 중국 단둥시에서 집에 앉아 압록강 철교를 감시하는 임무를 맡았다. 하지만 500만 원짜리 야간 근무를 기점으로 내게 자꾸 여러 나라가 엮이는 큰 사건이 터지기 시작했다.',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
  {
    slug: 'late-bloom',
    title: '늦바람',
    status: '연재중',
    creators: [{ role: '글', name: '과일차' }, { role: '그림', name: 'MUTE' }],
    platform: '네이버웹툰',
    serialType: '매일+',
    dayOfWeek: '일요일',
    startDate: '2026-03-21',
    episodeCount: 0,
    ageRating: '18+',
    mainGenre: '로맨스',
    subGenre: '19+',
    keywords: ['로맨스', '사연남', '고자극드라마'],
    element: '대한민국 상위 1%를 위한 아파트 ‘송더힐타운’을 배경으로 화려하고 안전하지만 그 아래 감춰진 통제와 폭력을 드러내는 치명적 로맨스 작품!',
    logline: '빚에 허덕이던 가족을 대신해 대부업자 이기택과 결혼한 유희나. 대한민국 최고급 주거 단지 송더힐타운에 입성하지만, 그녀의 삶은 철저한 통제 속에 놓인다. 외출 금지, 기록 공유, 남편의 허락 없는 일상은 존재하지 않는다.\n\n6년의 결혼 생활, 아이는 없고 남편의 폭력은 깊어간다. 남편의 외도를 목격한 뒤, 희나는 단지 내 수영장에 나가게 되고 그곳에서 수영강사 송지우를 만난다.\n\n물 위에서 시작된 작은 변화는, 닫혀 있던 그녀의 삶에 균열을 내기 시작하는데...',
    globalInfo: {},
    secondaryBiz: [],
    notes: '',
  },
];

export function getTitleBySlug(slug: string): TitleMasterInfo | undefined {
  return TITLE_MASTER_DATA.find((t) => t.slug === slug);
}

function normalize(s: string): string {
  return s.replace(/[\s\-_:!?·.,()（）\[\]【】]/g, '').toLowerCase();
}

const slugByNameCache: Record<string, string | null> = {};

export function getSlugByWorkName(workName: string): string | null {
  if (workName in slugByNameCache) return slugByNameCache[workName];

  const norm = normalize(workName);
  for (const t of TITLE_MASTER_DATA) {
    if (normalize(t.title) === norm) {
      slugByNameCache[workName] = t.slug;
      return t.slug;
    }
  }
  for (const t of TITLE_MASTER_DATA) {
    if (normalize(t.title).includes(norm) || norm.includes(normalize(t.title))) {
      slugByNameCache[workName] = t.slug;
      return t.slug;
    }
  }
  slugByNameCache[workName] = null;
  return null;
}
